force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Sr.No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Maintenance Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Confirmed</fullName>
                <default>true</default>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Registration Number</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Last_Known_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Last_Known_Odometer_Reading__c</fullName>
    <label>Last Known Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenanceRequestHelper.cls
public class MaintenanceRequestHelper {
    public static void createMaintenanceRequest(Map<Id, Vehicle__c> applicableRecords){
        List< Maintenance_Request__c> insertMrList = new List<Maintenance_Request__c>();
        List<Maintenance_Request__c> mrList = [SELECT Id,Vehicle_Registration_Number__c FROM Maintenance_Request__c WHERE Vehicle_Registration_Number__c in : applicableRecords.keySet() AND (Status__c !='Completed' OR Status__c != 'Cancelled')];
        for(Maintenance_Request__c mr : mrList){
            if(applicableRecords.containsKey(mr.Vehicle_Registration_Number__c)){
                applicableRecords.remove(mr.Vehicle_Registration_Number__c);
            }
        }
        for(Vehicle__c v: applicableRecords.values()){
            Maintenance_Request__c newMR = new Maintenance_Request__c();
            newMR.Vehicle_Registration_Number__c = v.Id;
            newMR.Maintenance_Date__c = Date.TODAY();
            newMR.Status__c = 'Not Confirmed';
            newMR.Odometer_Reading__c = v.Last_Known_Odometer_Reading__c;
            insertMrList.add(newMR);
        }
        if(insertMrList.size() > 0){
            insert insertMrList;
        }
    }
}