force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <displayFormat>MP-{0000}</displayFormat>
        <label>Sr.No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Maintenance_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request_Number__c</fullName>
    <label>Maintenance Request Number</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Qty_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Qty_Utilized__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty Utilized</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Sr.No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Maintenance Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Confirmed</fullName>
                <default>true</default>
                <label>Not Confirmed</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Registration Number</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/Part_Inventory__c.object-meta.xml
<CustomObject>
    <label>Part Inventory</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Inventory__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Qty_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Qty_Utilized__c</fullName>
    <label>Qty Utilized</label>
    <summarizedField>Maintenance_Part__c.Qty_Utilized__c</summarizedField>
    <summaryForeignKey>Maintenance_Part__c.Part_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Quantity_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Purchased__c</fullName>
    <label>Quantity Purchased</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Known_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Last_Known_Odometer_Reading__c</fullName>
    <label>Last Known Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MaintenanceRequestHelperTest.cls
@isTest
private class MaintenanceRequestHelperTest {
    @testSetup
    static void allTheDataForThisTestClass() {
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Contact contact = new Contact();
        contact.FirstName = 'test';
        contact.LastName = 'last';
        contact.Email = 'test@test.com';
        contact.AccountId = acc.Id;
        insert contact;
        
        Vehicle__c vehicle = new Vehicle__c();
        vehicle.Name = 'car';
        vehicle.Color__c = 'White';
        vehicle.Make__c = 'abc';
        vehicle.Model__c = 'car';
        vehicle.Year__c = '1990';
        vehicle.Vehicle_Owner__c = contact.Id;
        insert vehicle; 
        
        Maintenance_Request__c mReq= new Maintenance_Request__c ();
        mReq.Status__c ='Not Confirmed';
        mReq.Maintenance_Date__c = Date.today();
        mReq.Vehicle_Registration_Number__c = vehicle.Id;
        mReq.Odometer_Reading__c = 100000;
        insert mReq;
        
        Part_Inventory__c  parts= new Part_Inventory__c ();
        parts.Name='abc';
        parts.Part_Name__c='test';
        parts.Quantity_Purchased__c=1000;
        insert parts;
        
        Maintenance_Part__c  mParts = new Maintenance_Part__c();
        mParts.Part_Number__c = parts.Id;
        mParts.Qty_Utilized__c=10;
        mParts.Maintenance_Request_Number__c = mReq.Id;
        insert mParts;
    }
    
    static testMethod void testMaintenanceRequest() {
        List<Vehicle__c> vclList = new List<Vehicle__c>();
        List<Vehicle__c> secondList = new List<Vehicle__c>();
        
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'test' LIMIT 1]; 
        Contact contact  = [SELECT Id, FirstName, LastName,Email,AccountId FROM Contact WHERE Email = 'test@test.com' LIMIT 1]; 
        Vehicle__c vehicle = [SELECT Id, Name FROM Vehicle__c WHERE Name = 'car' LIMIT 1]; 
        Maintenance_Request__c mReq = [SELECT Id, Vehicle_Registration_Number__c FROM Maintenance_Request__c WHERE Vehicle_Registration_Number__c =: vehicle.Id LIMIT 1]; 
        Test.startTest();
        for(Integer i=1;i<=200;i++){
            Vehicle__c newVehicle = new Vehicle__c();
            newVehicle.Name = 'car'+String.valueOf(i);
            newVehicle.Color__c = 'White';
            newVehicle.Make__c = 'abc';
            newVehicle.Model__c = 'car';
            newVehicle.Year__c = '1990';
            newVehicle.Vehicle_Owner__c = contact.Id;
            vclList.add(newVehicle);   
        }
        
        insert vclList;
        
        // Assert your results!
        System.assertEquals(200,vclList.size());
        for(Vehicle__c vcl:vclList){
            vcl.Last_Known_Odometer_Reading__c  = 10000;
            secondList.add(vcl);
        }
        update secondList;
        List<Maintenance_Request__c> newMReq=[SELECT Id, Vehicle_Registration_Number__c FROM Maintenance_Request__c WHERE Vehicle_Registration_Number__c =:secondList];
        for(Maintenance_Request__c mr : newMReq){
            mr.Status__c = 'Completed';
        }
        update newMReq;
        secondList = new List<Vehicle__c>();
        for(Vehicle__c vcl:vclList){
            vcl.Last_Known_Odometer_Reading__c  = 30000;
            secondList.add(vcl);
        }
        update secondList;
        List<Vehicle__c> createdVehicles = [Select Id from Vehicle__c where Last_Known_Odometer_Reading__c = 30000];
        System.debug('###Size : '+createdVehicles.size());
        System.assertEquals(200,createdVehicles.size());
         
        //Remember to stop the test.
        Test.stopTest();
    } 
    static testMethod void testNonMaintenanceRequest() {
        Vehicle__c vcl=[SELECT Id, Last_Known_Odometer_Reading__c FROM Vehicle__c WHERE Name='car'];
        vcl.Last_Known_Odometer_Reading__c = 400;
        update vcl;
        
        vcl.Last_Known_Odometer_Reading__c = 1000;
        update vcl;
        
        vcl.Last_Known_Odometer_Reading__c = 10000;
        update vcl;
    }
}